### GENERAL SETTINGS ###

# Site settings
title: ULTRACOLD PROJECTS
description: "Following best practices, SOLID, 4 Pillars, writing code as cleanlz as possible..."
analytics: 
baseurl: "/ultracoldprojects" #important: start with /
url: "http://ultracold.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: twitter
    url: 
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Some Street, 999,
    - 12345 Somewhere.
email: someone@some.com
tel: +12 3478923847


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: ultracold
    position: all of them
    text: Something you really want to know.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@some.com
      - title: twitter
        url: http://twitter.com/handle
    
# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png

    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Something very illuminating."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "not bad, could be better."
    author: Some person
    position: CEO, back-of-beyond company
